### PR TITLE
Added Edit Customer Functionality

### PR DESCRIPTION
**Pull request by joelazwar**
### Description

Made additions to the Customer components to add edit functionality and updates the database. Most of the work was done in CustomerDetailsModal.tsx and CustomerTable.tsx

### Issue

Issue #327 

### Screenshots

papercups

## Checklist

- [x] Everything passes when running `mix test`
- [ ] Ran `mix format`
- [ ] No frontend compilation warnings

### CODE REVIEW

**Comment by reichert621** [comment]
@joelazwar thanks for tackling this! i'm a bit busy today but will try to review by end of day :)

**Comment by joelazwar** [comment]
@reichert621 That's alright, please let me know if any changes at all are necessary! Still a bit new to the technology and frameworks so the code might be a bit messy to say the least 😂

**Comment by reichert621** [comment]
hey @joelazwar! thanks for helping out with this :) I wanted to clean a few things up real quick, so I just pushed up some changes -- happy to discuss further if you want 👍

**Comment by joelazwar** [comment]
@reichert621 No problem, thanks for letting me contribute :) I'll go ahead and read your review changes to get some good insight

**Pull request merged**
