### PR TITLE
Mark multiple conversations as closed (WIP)

### PR DESCRIPTION
**Pull request by ZmagoD**
### Description

- Added checkboxes to every conversation, 
- Store the conversation id in an array

### Issue

https://github.com/papercups-io/papercups/issues/250

### Screenshots

WIP

Screenshot 2020-11-09 at 22 17 11

## Checklist

- [ ] Everything passes when running `mix test`
- [ ] Ran `mix format`
- [ ] No frontend compilation warnings

### CODE REVIEW

**Comment by reichert621** [comment]
thanks for getting started on this @ZmagoD! I think we'll definitely need to think about how to make this look nicer from a UI/UX perspective... might be worth taking a look at some other similar products (like Intercom) to see how they handle this

**Comment by ZmagoD** [comment]
HI @reichert621 when working on this I found a TODO comment and I'm a bit confused how to approach this task now
Screenshot 2020-12-01 at 21 36 59

Should we fire multiple queries or do a bulk update of selected items 🤔 

My idea was to create an endpoint that will handle status changes for multiple conversations but I'm not sure if it is a good idea anymore 🤔

**Comment by reichert621** [comment]
hey @ZmagoD sorry i missed this!

i would need to think about this a little bit more (it's currently a low priority 😓) -- but i think ideally we would do a "bulk update" to close them (i think this is how you were thinking?)

in the "bulk closing" case, we'll probably want to change the notification that pops up though... we definitely don't want to show a little notification toast for every single conversation that was closed!

**Comment by ZmagoD** [comment]
Hey @reichert621 I'm really sorry but I can't continue to work on this at the moment so I will close this PR if someone else wants to pick up this task.

**Pull request closed without merging**
