### PR TITLE
[WIP]: Add UI For Canned Responses 

### LINKED ISSUE #655: Set up UI for canned responses
**Problem**
Now that we have the APIs set up for canned responses, we should build out a simple UI where our users can create/view/edit/delete them :)

**Solution**
Set up a UI! Design TBD, but we can probably use Intercom for inspiration:

Screen Shot 2021-03-17 at 3 18 18 PM

To create a new canned response, we can probably just handle this in a modal with an input for "name" and a textarea for the "content".

(We can also stick with a simpler table UI to start off if that's easier)

**Testing**
Please include a screenshot in your PR.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by J0**
### Description

This Pull Request serves to add a User Interface for the canned responses pages. More details, screenshots, and documentation coming soon.

### Issue

Fix #655 

### Screenshots

WIP

## Checklist

- [ ] Everything passes when running `mix test`
- [ ] Ran `mix format`
- [ ] No frontend compilation warnings

### CODE REVIEW

**Comment by reichert621** [comment]
hey @J0 -- just wanted to clarify, canned responses are not conversations, but simply "saved replies"

**Comment by reichert621** [comment]
hey @J0 are you still working on this? is it ready for review? (i noticed it still says WIP)

**Comment by J0** [comment]
Hey @reichert621, 

Yes I still am. Would just like to confirm that the layout is correct before putting everything into place -- send you a DM on Slack a while ago. If you could take a look that'd be great!

**Comment by cheeseblubber** [comment]
Any updates on this one?

**Comment by J0** [comment]
Hey @cheeseblubber, 

Apologies, just minor updates. Should have time to look at it over the weekend(starts tmrw)

**Comment by J0** [comment]
Hey,

Due to personal reasons, I don't think I've the bandwidth to complete this PR within the next two months. I'm going to close this PR and unassign my self from this issue so that I don't block anyone from working on this. If there's still no one working on the issue after two months I'll come back to this.

Sorry about this.

**Pull request closed without merging**
