### PR TITLE
Fix metadata does not get updated

### LINKED ISSUE #995: Customer API endpoint doesn't update metadata
**Describe the bug**
After following the docs to update a customer, the metadata is always returned as `null`.

**To Reproduce**
1. Create an API key in the dashboard
2. Add your API key as a `Bearer` token & make a `GET` request to retrieve any customer `id` via `https://app.papercups.io/api/v1/customers/`
2. With that `id`, make a `PUT` request to `https://app.papercups.io/api/v1/customers/[id]/` with a body, ie:
```JSON
{
   "customer":{
      "metadata":{
         "random_custom_field":"034c0f85-0be3-4086-acf8-85ed8f4f1228"
      }
   }
}
```
3. You get a `200` but `data.metadata` is still `null`

**Expected behavior**
`data.metadata` would return the provided `"random_custom_field": "034c0f85-0be3-4086-acf8-85ed8f4f1228",`.

### PR DESCRIPTION
**Pull request by jeepers3327**
### Description

_Please describe the changes you made._
Currently the `metadata` key was dropped before it will be processed in a changeset. This PR preserved the `metadata` key until it is processed in Ecto changeset.

I'm not sure of it the function name is, and should it be in the `sanitize_metadata` pipeline or having to call it in controller after the `Customers.sanitize_metadata` function
### Issue

_Link to the issue (if available)_
This PR fixes #995 

I haven't added a test for this since I assumed  there is a recently pushed PR for metadata test.

### CODE REVIEW

**Comment by jeepers3327** [comment]
I'd like to ask for thoughts on my changes @reichert621.

**Comment by CharlesMangwa** [comment]
Hey @reichert621, @jeepers3327! Do you think you would be able to get this PR merged soon, please? I'd be incredibly valuable to us. Thanks again for your time! 🙌

**Comment by jeepers3327** [comment]
Hi @CharlesMangwa,

I'm not sure about that. It seems that the maintainer haven't reviewed my PR yet. I will try to reach out to them in slack if they can check on it.

**Comment by CharlesMangwa** [comment]
Hey @jeepers3327,

Thanks for the quick reply! I did see the maintenance announcement though I was under the impression that @reichert621 would consider this PR to fall into the exception mentioned in the 2nd sentence.

Regarding the Slack workspace, I believe [this message](https://papercups-io.slack.com/archives/C01AZQ73L5B/p1638616973003200) was coming from you?

**Comment by reichert621** [comment]
@jeepers3327 this issue isn't fresh in my mind, do you mind including test cases that demonstrate that the broken behavior is now fixed?

**Comment by jeepers3327** [comment]
Hi @reichert621

I updated the code and added a test.
Please check, thank you.

**Comment by jeepers3327** [comment]
@CharlesMangwa ,

Based on my code changes in this PR, If you want to update the metadata field, please update the param.

from:
```
{
   "customer":{
      "metadata":{
         "random_custom_field":"034c0f85-0be3-4086-acf8-85ed8f4f1228"
      }
   }
}
```

to:
```
{
   "customer":{
      "metadata":{
         "custom_metadata" =>  {
            "random_custom_field":"034c0f85-0be3-4086-acf8-85ed8f4f1228"
         }
      }
   }
}
```

**Comment by CharlesMangwa** [comment]
Hey @jeepers3327, thanks for the tests and steps! @reichert621 hopefully this PR is good for a merge now

**Comment by CharlesMangwa** [comment]
Hey @reichert621, checking again real quick if you'd have the time to review and potentially merge this PR this week by any chance, please?

**Comment by reichert621** [comment]
@CharlesMangwa @jeepers3327 this PR isn't really necessary, just do this: https://github.com/papercups-io/papercups/commit/6a6f5adc7f0cef5813b2c2f1c0659922defaf976

The API is a little weird I'll admit, but this endpoint isn't really meant to be used externally anyway 🤷

**Pull request closed without merging**
