### PR TITLE
Alphabetize Mix deps

### PR DESCRIPTION
**Pull request by a8t**
### Description

Here's a Hacktoberfest-tier PR...

Alphabetize Mix dependencies. It's not that important, but why not? ¯\\\_(ツ)_/¯

- [x] Everything passes when running `mix test`
- [x] Ran `mix format`
- [x] No frontend compilation warnings

(p.s. shout-out to whatever VS Code line sorter extension I have installed)

### CODE REVIEW

**Review by reichert621 — COMMENTED** [review]
seems reasonable! i wonder if there's a way to configure `mix format` (or some other pre-commit hook) to do this automatically 🤔

**Comment by a8t** [comment]
Short answer is "no" re: `mix format`. Slightly longer answer is that we can probably write a script that uses the [Code](https://hexdocs.pm/elixir/Code.html) module to parse the AST and maybe sort the Mix file, but that seems... kinda bad, kinda cool 🤔

**Comment by Divspy22d** [comment]
Good and awesome

**Comment by Divspy22d** [comment]
Screenshot_20210303-220726

**Comment by Divspy22d** [comment]
Nice update

**Pull request closed without merging**
