### PR TITLE
Update widget.js to v1.1.10

### PR DESCRIPTION
**Pull request by reichert621**
### Description

Update widget.js to v1.1.10 to enable popping up the initial message

## Checklist

- [x] Everything passes when running `mix test`
- [x] Ran `mix format`
- [x] No frontend compilation warnings

### CODE REVIEW

**Comment by a8t** [comment]
Does this fix the missing typescript type in the widget props?

**Comment by reichert621** [comment]
which type do you mean @a8t?

**Comment by a8t** [comment]
@reichert621 - I'm getting a TS error for `awayMessage` on the head of master.

**Comment by a8t** [comment]
image

**Comment by reichert621** [comment]
ah @a8t you might need to run `npm install` in the `/assets` directory?

**Comment by reichert621** [comment]
(the update in this PR only deals with the js script that can be pasted in the html, so it doesn't have anything to do with typescript)

**Comment by a8t** [comment]
> ah @a8t you might need to run `npm install` in the `/assets` directory?

lol you were right!

**Pull request merged**
