### PR TITLE
Allow admin users to disable members on their account

### PR DESCRIPTION
**Pull request by reichert621**
Screen Shot 2020-09-22 at 2 28 34 PM
Screen Shot 2020-09-22 at 2 26 00 PM

### CODE REVIEW

**Review by reichert621 — COMMENTED** [review]
add some more tests and then this should be good to go!

**Comment by MuhammadMullah** [comment]
I am not a react guy. But I have gone through the whole code and more specifically the elixir code and it looks good to me. But out of curiosity or let me say learning from each other. For me, I would have made disabled_at to be a boolean with default as false, and whenever I disable a user its just a matter of updating it to true.

maybe if you can shed light on me on the decision on why you made disabled_at as utc_datetime?

**Comment by MuhammadMullah** [comment]
also couldn't some of those functions be private e.g archive_user, disable_user, enable_user, or are they being used anywhere else outside of that module?

**Comment by reichert621** [comment]
hey @MuhammadMullah! great questions :) 

- in terms of using `disabled_at` as a datetime rather than a boolean, this is a common pattern used because it gives you more information with the same functionality -- for example, it's often helpful to know exactly when a user was archived or disabled, and you can infer if the user is disabled based on the presence of that field (i.e. if it's `null`, then they user is not disabled)
- those methods are currently used in the `UserController`, so they can't be private unfortunately 

let me know if you have anymore questions!

**Comment by MuhammadMullah** [comment]
> * those methods are currently used in the `UserController`, so they can't be private unfortunately
>  ooh maybe I was not careful to check that. Okay great, thanks

**Pull request merged**
