### PR TITLE
Show also email if (name && email)

### PR DESCRIPTION
**Pull request by webdeb**
Bildschirmfoto 2020-08-12 um 11 50 24

### CODE REVIEW

**Comment by reichert621** [comment]
great idea! can you take a screenshot of the full header? just want to make sure the alignment looks ok :)

**Comment by webdeb** [comment]
Bildschirmfoto 2020-08-13 um 00 53 47

The wrapper flex container has alignItems baseline, maybe center is a better choice? see below:

Bildschirmfoto 2020-08-13 um 00 56 35

**Comment by webdeb** [comment]
...pushed with "center" and did a rebase, looks nice imho

**Comment by webdeb** [comment]
happy to contribute :)

**Pull request merged**
